name = "Riftbound"
code = "riftbound"
font-version = "0.2.0"
colr-version = "v1"

[[categories]]
name = "symbol"

[[categories]]
name = "domain"

[[categories]]
name = "number"

[[styles]]
name = "default"

[[styles]]
name = "inverted"

[compose]
