"""Package consumer artifacts into packages/fonts/<game>/.

Produces a single CSS declaring both @font-face entries, the WOFF2
files, and a metadata JSON. Output is generated and gitignored.
"""
from __future__ import annotations

import json
from pathlib import Path

from .build import flavor_specs
from .model import GameData

FAMILY_FULL = "Sigilora {Game}"
FAMILY_LITE = "Sigilora {Game} Lite"


def _font_face(family: str, file: str) -> str:
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        f'  src: url("{file}") format("woff2");\n'
        "  font-weight: normal;\n"
        "  font-style: normal;\n"
        "}"
    )


def package(game: GameData, build_dir: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    game_label = game.code.capitalize()
    family_full = FAMILY_FULL.format(Game=game_label)
    family_lite = FAMILY_LITE.format(Game=game_label)

    # Consumer WOFF2 set per family (see flavor_specs): the primary flavor plus,
    # where a family is COLRv1 with a [colr-fallback], the -v0 COLRv0 fallback.
    families = [(False, game.code, family_full),
                (True, f"{game.code}-lite", family_lite)]
    for lite, base, _family in families:
        lite_part = "-Lite" if lite else ""
        for spec in flavor_specs(game, lite):
            suffix = spec["suffix"]
            src = build_dir / f"Sigilora-{game_label}{lite_part}-{game.font_version}{suffix}.woff2"
            if not src.exists():
                raise FileNotFoundError(f"missing built font: {src}")
            (out_dir / f"{base}{suffix}.woff2").write_bytes(src.read_bytes())

    css = [f"/* Sigilora {game_label} — generated by sigilora package */"]
    for lite, base, family in families:
        specs = flavor_specs(game, lite)
        primary = next(s for s in specs if s["suffix"] == "")
        if len(specs) > 1:
            fallback = next(s for s in specs if s["suffix"] == "-v0")
            # Fail closed: engines that do not understand COLRv1 (or the
            # font-tech() query) load the COLRv0 fallback; COLRv1-capable
            # engines override it with the v1 flavor.
            css.append(_font_face(family, f"{base}{fallback['suffix']}.woff2"))
            inside = "\n".join(
                "  " + line for line in _font_face(family, f"{base}{primary['suffix']}.woff2").splitlines()
            )
            css.append("@supports font-tech(color-COLRv1) {")
            css.append(inside)
            css.append("}")
        else:
            css.append(_font_face(family, f"{base}{primary['suffix']}.woff2"))
    (out_dir / f"{game.code}.css").write_text("\n".join(css) + "\n", encoding="utf-8")

    meta = {
        "game": game.code,
        "name": game.name,
        "font-version": game.font_version,
        "colr-version": game.colr_version,
        "fonts": [
            {"family": family_full, "file": f"{game.code}.woff2", "styles": game.style_order,
             "colr-version": game.colr_version},
            {"family": family_lite, "file": f"{game.code}-lite.woff2", "styles": ["default"],
             "colr-version": game.lite_colr_version},
        ],
        "symbols": len(game.symbols),
        "categories": [c["name"] for c in game.categories],
    }
    (out_dir / f"{game.code}.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    symbols = [
        {
            "name": s.name,
            "ligature": s.ligature,
            "category": s.category,
            "styles": list(s.svg.keys()),
            "overflow": s.overflow,
        }
        for s in game.symbols
    ]
    (out_dir / f"{game.code}-symbols.json").write_text(
        json.dumps(symbols, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
