"""Package consumer artifacts into packages/fonts/<game>/.

Produces a single CSS declaring both @font-face entries, the WOFF2
files, and a metadata JSON. Output is generated and gitignored.
"""
from __future__ import annotations

import json
from pathlib import Path

from .model import GameData

FAMILY_FULL = "Sigilora {Game}"
FAMILY_LITE = "Sigilora {Game} Lite"


def package(game: GameData, build_dir: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    game_label = game.code.capitalize()

    full_ttf = build_dir / f"Sigilora-{game_label}-{game.font_version}.ttf"
    lite_ttf = build_dir / f"Sigilora-{game_label}-Lite-{game.font_version}.ttf"
    for src, dst in ((full_ttf.with_suffix(".woff2"), out_dir / "magic.woff2"),
                     (lite_ttf.with_suffix(".woff2"), out_dir / "magic-lite.woff2")):
        if not src.exists():
            raise FileNotFoundError(f"missing built font: {src}")
        dst.write_bytes(src.read_bytes())

    family_full = FAMILY_FULL.format(Game=game_label)
    family_lite = FAMILY_LITE.format(Game=game_label)
    css = f"""\
/* Sigilora {game_label} — generated by sigilora-build package */
@font-face {{
  font-family: "{family_full}";
  src: url("magic.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
}}
@font-face {{
  font-family: "{family_lite}";
  src: url("magic-lite.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
}}
"""
    (out_dir / "magic.css").write_text(css, encoding="utf-8")

    meta = {
        "game": game.code,
        "name": game.name,
        "font-version": game.font_version,
        "colr-version": game.colr_version,
        "fonts": [
            {"family": family_full, "file": "magic.woff2", "styles": game.style_order},
            {"family": family_lite, "file": "magic-lite.woff2", "styles": ["default"]},
        ],
        "symbols": len(game.symbols),
        "categories": [c["name"] for c in game.categories],
    }
    (out_dir / "magic.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    symbols = [
        {
            "name": s.name,
            "ligature": s.ligature,
            "display-name": s.display_name,
            "category": s.category,
            "styles": list(s.svg.keys()),
        }
        for s in game.symbols
    ]
    (out_dir / "symbols.json").write_text(
        json.dumps(symbols, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
