name = "Magic: The Gathering"
code = "magic"
font-version = "1.2.1"
colr-version = "v0"

[[categories]]
name = "normal-mana"

[[categories]]
name = "number-mana"

[[categories]]
name = "hybrid-mana"

[[categories]]
name = "phyrexian-mana"

[[categories]]
name = "other"

[[categories]]
name = "special"

[[categories]]
name = "loyalty"

[[styles]]
name = "default"

[[styles]]
name = "shadow"

[[styles]]
name = "flat"

[compose.shadow]
offset = [8, 8]
viewbox = "0 0 108 100"

[compose.flat-simple]
scale = 0.9
fill-map = { "#CAC5C0" = "#000000", "#FFFCD5" = "#ABA18A", "#ABE1FA" = "#0172BB", "#F9AA8F" = "#FD2302", "#9BD3AE" = "#027920", "#C3BAB9" = "#000000", "#EAE3B1" = "#ABA18A", "#8EBBD0" = "#0172BB", "#9A8D89" = "#281C1C", "#DF8065" = "#FD2302", "#80B092" = "#027920", "#CCC2C0" = "#000000" }

[compose.flat-complex]
part-up-transform = "translate(32.32, 32.32) scale(0.9) translate(-32.32, -32.32)"
part-down-transform = "translate(67.68, 67.68) scale(0.9) translate(-67.68, -67.68)"

[compose.loyalty]
font-size = 60
